### ISSUE TITLE
Making this works with inertia team.

### ISSUE THREAD

**Issue by novashockinc** [coolsam726/jetstream-inertia-generator#20]
It will be nice if this could work with jetstream InertiaJS?

**Comment by coolsam726** [comment]
Hi @novashockinc ,

Do you mean supporting the Jetstream Teams feature?

**Comment by coolsam726** [comment]
The package is actually a build-up on Jetstream and InertiaJS stack, so ALL the features that Jetstream supports remain intactly supported by JIG as well. If you experience any challenge, feel free to share.
