### ISSUE TITLE
DataTables warning: table id=users-dt - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by yorizpra** [coolsam726/jetstream-inertia-generator#47]
**Bug Description**
When i try to click backend modules it sends "DataTables warning: table id=users-dt - Ajax error. For more information about this error, please see http://datatables.net/tn/7" error

**To Reproduce**
1. After install jig and 'php artisan serve' and login. Go to 'backend'
2. Click on 'permissions or roles or users'
3. It will show pop up and display the error with 'DataTables warning: table id=users-dt - Ajax error. For more information about this error, please see http://datatables.net/tn/7'

**Expected behavior**
I dont know why this is happen, it's my first time use jig, maybe the problem is yajra datatables

**Screenshots**
I want to share a screenshot but i don't know how to do it, i will send it later after i find out

**Desktop:**
 - OS: [windows 11 pro]
 - Browser [microsoft edge]

**Comment by rakoi** [comment]
Have you run your migrations?

**Comment by coolsam726** [comment]
@yorizpra  you could also check if you skipped any step in configuration. I especially suspect that it is related to SANCTUM configuration. Ensure you have **SANCTUM_STATEFUL_DOMAINS="${APP_BASE_DOMAIN}"** in your .env file.

However, please try to see what is the exact error sent from the backend by checking the browser's network tab in dev mode for the exact response.

If you continue getting these challenges while configuring and your project is in its early stages, I recommend that you use the ready-made starter template which has all the configs ready. [You can find it here](https://github.com/savannabits/jig)
